
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPAREN = 3;
  public static final int ASSERT = 11;
  public static final int DECREMENT = 9;
  public static final int TRUE = 13;
  public static final int LPAREN = 2;
  public static final int ID = 17;
  public static final int ODD = 15;
  public static final int ANY_INT = 4;
  public static final int EQUALS = 6;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int ASSUME = 10;
  public static final int INCREMENT = 8;
  public static final int EVEN = 16;
  public static final int FALSE = 14;
  public static final int error = 1;
  public static final int ASSIGN = 5;
  public static final int NEQUALS = 7;
  public static final int SKIP = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "ANY_INT",
  "ASSIGN",
  "EQUALS",
  "NEQUALS",
  "INCREMENT",
  "DECREMENT",
  "ASSUME",
  "ASSERT",
  "SKIP",
  "TRUE",
  "FALSE",
  "ODD",
  "EVEN",
  "ID",
  "NUMBER"
  };
}

